version: "3.7"
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:0.8.0
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/data/configs
    ports:
      - ${APP_PORT}:7575
    networks:
      - tipi_main_network
