version: "3.7"
services:
  activepieces:
    image: activepieces/activepieces:0.12.2
    container_name: activepieces
    restart: unless-stopped
    ports:
      - "{APP_PORT}:80"
    depends_on:
      - activepieces-postgres
      - activepieces-redis
    environment:
      - POSTGRES_DB=activepieces
      - POSTGRES_PASSWORD=${AP_POSTGRES_PASSWORD}
      - POSTGRES_USER=tipi
    networks:
     - tipi_main_network
    
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.activepieces-web-redirect.redirectscheme.scheme: https
      traefik.http.services.activepieces.loadbalancer.server.port: 8744
      # Web
      traefik.http.routers.activepieces-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.activepieces-insecure.entrypoints: web
      traefik.http.routers.activepieces-insecure.service: activepieces
      traefik.http.routers.activepieces-insecure.middlewares: activepieces-web-redirect
      # Websecure
      traefik.http.routers.activepieces.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.activepieces.entrypoints: websecure
      traefik.http.routers.activepieces.service: activepieces
      traefik.http.routers.activepieces.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.activepieces-local-insecure.rule: Host(`activepieces.${LOCAL_DOMAIN}`)
      traefik.http.routers.activepieces-local-insecure.entrypoints: web
      traefik.http.routers.activepieces-local-insecure.service: activepieces
      traefik.http.routers.activepieces-local-insecure.middlewares: activepieces-web-redirect
      # Local domain secure
      traefik.http.routers.activepieces-local.rule: Host(`activepieces.${LOCAL_DOMAIN}`)
      traefik.http.routers.activepieces-local.entrypoints: websecure
      traefik.http.routers.activepieces-local.service: activepieces
      traefik.http.routers.activepieces-local.tls: true

  activepieces-postgres:
    image: postgres:activepieces-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=activepieces
      - POSTGRES_PASSWORD=${AP_POSTGRES_PASSWORD}
      - POSTGRES_USER=tipi
    volumes:
      - "{APP_DATA}/data/postgres:/var/lib/postgresql/data"
    networks:
      - tipi_main_network

  activepieces-redis:
    image: redis:7
    container_name: activepieces-redis
    restart: unless-stopped
    volumes:
      - "{APP_DATA}/data/redis/:/data"
    networks:
      - tipi_main_network
