version: "3.7"

services:
  server:
    container_name: simple-torrent
    image: boypt/cloud-torrent:1.3.9
    restart: on-failure
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: >
      --port=${APP_PORT}
      --config-path /config/simple-torrent.json
    volumes:
      - ${APP_DATA_DIR}/data/torrents:/torrents
      - ${APP_DATA_DIR}/data/downloads:/downloads
      - ${APP_DATA_DIR}/data/config:/config
    networks:
        - tipi_main_network
    # labels:
    #     traefik.enable: true
    #     traefik.http.routers.simple-torrent.rule: Host(`simple-torrent.tipi.home`)
    #     traefik.http.routers.simple-torrent.service: simple-torrent
    #     traefik.http.routers.simple-torrent.tls: true
    #     traefik.http.routers.simple-torrent.entrypoints: websecure
    #     traefik.http.services.simple-torrent.loadbalancer.server.port: ${APP_SIMPLETORRENT_PORT}