version: '3.9'
services:
  actual-server:
    container_name: actual-server
    image: actualbudget/actual-server:23.4.2
    restart: unless-stopped
    ports:
      - ${APP_PORT}:5006
    networks:
      - tipi_main_network
    volumes:
    - ${APP_DATA_DIR}/data:/data
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.actual-server.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.actual-server.entrypoints: websecure
      traefik.http.routers.actual-server.service: actual-server
      traefik.http.routers.actual-server.tls.certresolver: myresolver
      traefik.http.services.actual-server.loadbalancer.server.port: 5006
