
version: '3'
services:
  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - TZ=${TZ}
    volumes:
      - ${APP_DATA_DIR}/data/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.homebridge-web-redirect.redirectscheme.scheme: https
      traefik.http.services.homebridge.loadbalancer.server.port: 8581
      # Local domain
      traefik.http.routers.homebridge-local-insecure.rule: Host(`homebridge.${LOCAL_DOMAIN}`)
      traefik.http.routers.homebridge-local-insecure.middlewares: homebridge-web-redirect
      # Local domain secure
      traefik.http.routers.homebridge-local.rule: Host(`homebridge.${LOCAL_DOMAIN}`)
      traefik.http.routers.homebridge-local.tls: true