version: "3"

services:
  emulatorjs:
    container_name: emulatorjs
    image: lscr.io/linuxserver/emulatorjs:1.7.2
    ports:
      - ${APP_PORT}:80
      - 8165:3000
    volumes:
      - ${APP_DATA_DIR}/data/emulatorjs-config:/config #Path to store user profiles
      - ${APP_DATA_DIR}/data/emulatorjs:/data #Path to store roms/artwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.emulatorjs.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.appname.entrypoints: websecure
      traefik.http.routers.emulatorjs.service: emulatorjs
      traefik.http.routers.emulatorjs.tls.certresolver: myresolver
      traefik.http.services.emulatorjs.loadbalancer.server.port: 80
