version: "3.9"

services:
  kanboard:
    container_name: kanboard
    image: kanboard/kanboard:v1.2.28
    environment:
      - PLUGIN_INSTALLER = true
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/kanboard_data:/var/www/app/data
      - ${APP_DATA_DIR}/data/kanboard_plugins:/var/www/app/plugins
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.it-tools.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.it-tools.entrypoints: websecure
      traefik.http.routers.it-tools.service: kanboard
      traefik.http.routers.it-tools.tls.certresolver: myresolver
      traefik.http.services.it-tools.loadbalancer.server.port: 80