services:
  filerun-db:
    container_name: filerun-db
    user: 1000:1000
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: tipi
      MYSQL_USER: tipi
      MYSQL_PASSWORD: tipi
      MYSQL_DATABASE: tipi
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/mysql
    networks:
      - tipi_main_network

  filerun:
    container_name: filerun
    image: filerun/filerun:arm64v8
    environment:
      FR_DB_HOST: filerun-db
      FR_DB_PORT: 3306
      FR_DB_NAME: tipi
      FR_DB_USER: tipi
      FR_DB_PASS: tipi
      APACHE_RUN_USER: 1000
      APACHE_RUN_GROUP: 1000
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - db
    links:
      - db:db
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${ROOT_FOLDER_HOST}/app-data/medias:/user-files
    networks:
      - tipi_main_network
