version: "3.7"

services:
  hedgedoc:
    # Make sure to use the latest release from https://hedgedoc.org/latest-release
    image: quay.io/hedgedoc/hedgedoc:1.9.7
    environment:
      - CMD_DB_URL=postgres://hedgedoc:${DB_PASSWORD}@hedgedoc-db:5432/hedgedoc
      - CMD_DOMAIN=${APP_DOMAIN}
      - CMD_URL_ADDPORT=${CMD_URL_ADDPORT}
    volumes:
      - ${APP_DATA_DIR}/data/hedgedoc-uploads:/hedgedoc/public/uploads
    ports:
      - ${APP_PORT}:3000
    restart: always
    depends_on:
      - hedgedoc-db
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.hedgedoc.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.hedgedoc.entrypoints: websecure
      traefik.http.routers.hedgedoc.service: hedgedoc
      traefik.http.routers.hedgedoc.tls.certresolver: myresolver
      traefik.http.services.hedgedoc.loadbalancer.server.port: 3000
  hedgedoc-db:
    container_name: hedgedoc-db
    image: postgres:13.4-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=hedgedoc
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=hedgedoc
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    networks:
      - tipi_main_network
