version: "3"

services:
  dokuwiki:
    container_name: dokuwiki
    image: lscr.io/linuxserver/dokuwiki:2022-07-31a-ls158
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.dokuwiki.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.dokuwiki.entrypoints: websecure
      traefik.http.routers.dokuwiki.service: dokuwiki
      traefik.http.routers.dokuwiki.tls.certresolver: myresolver
      traefik.http.services.dokuwiki.loadbalancer.server.port: 80