version: "3"

services:
  appname:
    container_name: openbooks
    image: evanbuss/openbooks:4.5.0
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${ROOT_FOLDER_HOST}/media/data/books/openbooks:/books
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.openbooks.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.openbooks.entrypoints: websecure
      traefik.http.routers.openbooks.service: openbooks
      traefik.http.routers.openbooks.tls.certresolver: myresolver
      traefik.http.services.openbooks.loadbalancer.server.port: 80
