name: Update app version in Renovate Branches

on:
  push:
    branches: [ 'renovate/*' ]
    
jobs:
  update-app-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Configure repo
        run: |
          git config --local user.email "githubaction@githubaction.com"
          git config --local user.name "github-action update-app-version"
      
      - name: Update app version
        run: |
          ./.github/workflows/renovate-app-version.sh
      
      - name: Commit & Push Changes
        run: |
          git add "apps/*/config.json" && git commit -m "Update app version" && git push || true
